apiVersion: apps/v1
kind: Deployment
metadata:
  name: smey-rails-3-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smey-rails-3-image
  template:
    metadata:
      labels:
        app: smey-rails-3-image
    spec:
      containers:
        - name: smey-rails-3-image
          image: smey-rails-3-image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP

