---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/prime_numbers/calculate?max_number=-10":
    get:
      summary: return invalid if max number is negative
      responses:
        '422':
          description: 'Invalid Input: Max number should be positive.'
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
